# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  name "flow"
  desc ""
  homepage "https://flowexec.io"
  version "2.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"
  bash_completion "scripts/completions/flow.bash"
  zsh_completion "scripts/completions/flow.zsh"
  fish_completion "scripts/completions/flow.fish"

  on_macos do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_darwin_amd64.tar.gz"
      sha256 "ace7189f88da3024a44eb588a33c1dc0dcdbef77834571523db6db349514a28f"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_darwin_arm64.tar.gz"
      sha256 "cb23f0d028064e5a8e852ee74fc4ee122e1f9413774b421a429d29fac1a2e65f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_linux_amd64.tar.gz"
      sha256 "1c2a8b954507f8a4eb339538e2d0f87c7fff868f446f5318bbf05c3e8517ae3f"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_linux_arm64.tar.gz"
      sha256 "c81b917ade3a85334e18497bb1d7e4e1bb5213f511e284e36bd68f7731324de7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flow"]
    end
  end

  # No zap stanza required
end
