# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  name "flow"
  desc ""
  homepage "https://flowexec.io"
  version "2.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"
  bash_completion "scripts/completions/flow.bash"
  zsh_completion "scripts/completions/flow.zsh"
  fish_completion "scripts/completions/flow.fish"

  on_macos do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_darwin_amd64.tar.gz"
      sha256 "d4794a9b7313bf11e151e17d695287cdc5596956bcc22d4bf5f80cab8cfd5c56"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_darwin_arm64.tar.gz"
      sha256 "2575cd78d7486da54913fb3e097570b705edb0b71ac780725d6cedcaad90ff41"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_linux_amd64.tar.gz"
      sha256 "318b88d54f9a36ec2660f4e186fcd629a29baaf2765551b80c43e1f572680493"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_linux_arm64.tar.gz"
      sha256 "b63d41a783c7020fdf50edf10eba06ac14904313d0a68c544b184eb30f4f55a7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flow"]
    end
  end

  # No zap stanza required
end
