# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  name "flow"
  desc ""
  homepage "https://flowexec.io"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"
  bash_completion "scripts/completions/flow.bash"
  zsh_completion "scripts/completions/flow.zsh"
  fish_completion "scripts/completions/flow.fish"

  on_macos do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_darwin_amd64.tar.gz"
      sha256 "2c78bb3b530519b6cef8303df4e04588d91f54e1fa87552b95e56f8d35577355"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_darwin_arm64.tar.gz"
      sha256 "287dd9b26abd0f25d1e2f8a1fb58cce05c2848bdd06314f252bfb120777436cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_linux_amd64.tar.gz"
      sha256 "24006eb873eb093b5b967e4aaed66bbbaae4e7c09327560dbfb9146c4b032b9f"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_linux_arm64.tar.gz"
      sha256 "ff4ed81ddeeda5539d37c21ff191b1d2627b78e15e2e9ee00a7a14dfedabb7dc"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flow"]
    end
  end

  # No zap stanza required
end
